import Tool from '../components/Tool'

export const tools = [
    <Tool
        key="1"
        link="https://www.gnu.org/software/bash"
        image="https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg"
        title="Bash"
    />,
    <Tool
        key="2"
        link="https://www.docker.com"
        image="https://www.vectorlogo.zone/logos/docker/docker-icon.svg"
        title="Docker"
    />,
    <Tool
        key="3"
        link="https://www.jenkins.io"
        image="https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg"
        title="Jenkins"
    />,
    <Tool
        key="4"
        link="https://www.nginx.com"
        image="https://www.vectorlogo.zone/logos/nginx/nginx-icon.svg"
        title="Nginx"
    />,
    <Tool
        key="5"
        link="https://nodejs.org"
        image="https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg"
        title="NodeJS"
    />,
    <Tool
        key="6"
        link="https://expressjs.com/"
        image="https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg"
        title="Express"
    />,
    <Tool
        key="7"
        link="https://postman.com"
        image="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
        title="Postman"
    />,
    <Tool
        key="8"
        link="https://heroku.com"
        image="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg"
        title="Heroku"
    />,
    <Tool
        key="9"
        link="https://firebase.google.com"
        image="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
        title="Firebase"
    />,
    <Tool
        key="10"
        link="https://cloud.google.com"
        image="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg"
        title="Google Cloud"
    />,
    <Tool
        key="11"
        link="https://grafana.com"
        image="https://www.vectorlogo.zone/logos/grafana/grafana-icon.svg"
        title="Grafana"
    />,
    <Tool
        key="12"
        link="https://www.mongodb.com"
        image="https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg"
        title="MongoDB"
    />,
    <Tool
        key="13"
        link="https://www.mysql.com"
        image="https://www.vectorlogo.zone/logos/mysql/mysql-icon.svg"
        title="MySQL"
    />,
    <Tool
        key="14"
        link="https://www.sqlite.org"
        image="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
        title="SQLite"
    />,
    <Tool
        key="15"
        link="https://www.postgresql.org"
        image="https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg"
        title="PostgreSQL"
    />,
    <Tool
        key="16"
        link="https://graphql.org"
        image="https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg"
        title="GraphQL"
    />,
    <Tool
        key="17"
        link="https://jestjs.io"
        image="https://www.vectorlogo.zone/logos/jestjsio/jestjsio-icon.svg"
        title="Jest"
    />,
    <Tool
        key="18"
        link="https://www.elastic.co"
        image="https://www.vectorlogo.zone/logos/elastic/elastic-icon.svg"
        title="Elastic"
    />,
    <Tool
        key="19"
        link="https://www.figma.com"
        image="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
        title="Figma"
    />,
    <Tool
        key="20"
        link="https://www.sketch.com"
        image="https://www.vectorlogo.zone/logos/sketchapp/sketchapp-icon.svg"
        title="Sketch"
    />,
    <Tool
        key="21"
        link="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        image="https://www.vectorlogo.zone/logos/javascript/javascript-icon.svg"
        title="JavaScript"
    />,
    <Tool
        key="22"
        link="https://www.typescriptlang.org"
        image="https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg"
        title="TypeScript"
    />,
    <Tool
        key="23"
        link="https://getbootstrap.com"
        image="https://www.vectorlogo.zone/logos/getbootstrap/getbootstrap-icon.svg"
        title="Bootstrap"
    />,
    <Tool
        key="24"
        link="https://tailwindcss.com"
        image="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
        title="Tailwind"
    />,
    <Tool
        key="25"
        link="https://www.w3.org/html"
        image="https://www.vectorlogo.zone/logos/w3_html5/w3_html5-icon.svg"
        title="HTML5"
    />,
    <Tool
        key="26"
        link="https://www.w3schools.com/css"
        image="https://www.vectorlogo.zone/logos/w3_css/w3_css-icon.svg"
        title="CSS3"
    />,
    <Tool
        key="27"
        link="https://sass-lang.com"
        image="https://www.vectorlogo.zone/logos/sass-lang/sass-lang-icon.svg"
        title="Sass"
    />,
    <Tool
        key="28"
        link="https://webpack.js.org"
        image="https://www.vectorlogo.zone/logos/js_webpack/js_webpack-icon.svg"
        title="Webpack"
    />,
    <Tool
        key="29"
        link="https://reactjs.org"
        image="https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg"
        title="React"
    />,
    <Tool
        key="30"
        link="https://www.gatsbyjs.com"
        image="https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg"
        title="Gatsby"
    />,
    <Tool
        key="31"
        link="https://www.electronjs.org/"
        image="https://www.vectorlogo.zone/logos/electronjs/electronjs-icon.svg"
        title="Electron"
    />,
    <Tool
        key="32"
        link="https://git-scm.com"
        image="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
        title="Git"
    />
]
